export enum AuthErrorCode {
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  PHOHE_ALREADY_EXISTS = "PHOHE_ALREADY_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  WEAK_PASSWORD = "WEAK_PASSWORD",
  INVALID_EMAIL = "INVALID_EMAIL",
  SERVER_ERROR = "SERVER_ERROR",
  REGISTRATION_BLOCKED = "REGISTRATION_BLOCKED",
}